### ISSUE TITLE
about the param.yaml(how to product)

### ISSUE THREAD

**Issue by Onehundred0906** [TexasInstruments/edgeai-benchmark#12]
excuse me 
 can you explain how i can product the .yaml file of my model in details?  or i need to learn which scripts?
thanks
![2022-12-01 17-30-45屏幕截图](https://user-images.githubusercontent.com/111262872/205017298-e55e7c0f-c121-4dc2-b486-6b5a04db75e6.png)

**Comment by mathmanu** [comment]
For compiling your own models and producing compiled output, you can use the following script:
https://github.com/TexasInstruments/edgeai-benchmark/blob/master/run_custom_pc.sh
Which invokes this: https://github.com/TexasInstruments/edgeai-benchmark/blob/master/scripts/benchmark_custom.py

See the above script and modify it to compile your own model.

**Comment by Onehundred0906** [comment]
Hello,i'm sorry to bother again. when i compile my model trained on my own datasets, some mistake occurs like that:
(benchmark) valeo22@valeo22:~/edgeai-benchmark$ ./run_custom_pc.sh 
Entering: ./work_dirs/modelartifacts/8bits/od-5040_tvmdlr_coco_gluoncv-mxnet_ssd_512_mobilenet1.0_coco-symbol_json.tar.gz.link
run_set_target_machine.sh: 第 59 行: cd: ./work_dirs/modelartifacts/8bits/od-5040_tvmdlr_coco_gluoncv-mxnet_ssd_512_mobilenet1.0_coco-symbol_json.tar.gz.link/artifacts: 不是目录
Entering: ./work_dirs/modelartifacts/8bits/ss-5710_tvmdlr_cocoseg21_edgeai-tv_deeplabv3plus_mobilenetv2_edgeailite_512x512_20210405_onnx.tar.gz.link
run_set_target_machine.sh: 第 59 行: cd: ./work_dirs/modelartifacts/8bits/ss-5710_tvmdlr_cocoseg21_edgeai-tv_deeplabv3plus_mobilenetv2_edgeailite_512x512_20210405_onnx.tar.gz.link/artifacts: 不是目录
Entering: ./work_dirs/modelartifacts/8bits/cl-3420_tvmdlr_imagenet1k_gluoncv-mxnet_resnet50_v1d-symbol_json.tar.gz.link
run_set_target_machine.sh: 第 59 行: cd: ./work_dirs/modelartifacts/8bits/cl-3420_tvmdlr_imagenet1k_gluoncv-mxnet_resnet50_v1d-symbol_json.tar.gz.link/artifacts: 不是目录
Entering: ./work_dirs/modelartifacts/8bits/cl-3090_tvmdlr_imagenet1k_torchvision_mobilenet_v2_tv_onnx.tar.gz.link
run_set_target_machine.sh: 第 59 行: cd: ./work_dirs/modelartifacts/8bits/cl-3090_tvmdlr_imagenet1k_torchvision_mobilenet_v2_tv_onnx.tar.gz.link/artifacts: 不是目录
Entering: ./work_dirs/modelartifacts/8bits/ss-5720_tvmdlr_cocoseg21_edgeai-tv_fpn_aspp_regnetx800mf_edgeailite_512x512_20210405_onnx.tar.gz.link
run_set_target_machine.sh: 第 59 行: cd: ./work_dirs/modelartifacts/8bits/ss-5720_tvmdlr_cocoseg21_edgeai-tv_fpn_aspp_regnetx800mf_edgeailite_512x512_20210405_onnx.tar.gz.link/artifacts: 不是目录
Entering: ./work_dirs/modelartifacts/8bits/od-5020_tvmdlr_coco_gluoncv-mxnet_yolo3_mobilenet1.0_coco-symbol_json.tar.gz.link
run_set_target_machine.sh: 第 59 行: cd: ./work_dirs/modelartifacts/8bits/od-5020_tvmdlr_coco_gluoncv-mxnet_yolo3_mobilenet1.0_coco-symbol_json.tar.gz.link/artifacts: 不是目录
Entering: ./work_dirs/modelartifacts/8bits/od-5030_tvmdlr_coco_gluoncv-mxnet_ssd_512_resnet50_v1_coco-symbol_json.tar.gz.link
run_set_target_machine.sh: 第 59 行: cd: ./work_dirs/modelartifacts/8bits/od-5030_tvmdlr_coco_gluoncv-mxnet_ssd_512_resnet50_v1_coco-symbol_json.tar.gz.link/artifacts: 不是目录
Entering: ./work_dirs/modelartifacts/8bits/ss-5818_tvmdlr_ti-robokit_edgeai-tv_deeplabv3plus_mobilenetv2_tv_edgeailite_robokit-zed1hd_768x432_qat-p2_onnx.tar.gz.link
run_set_target_machine.sh: 第 59 行: cd: ./work_dirs/modelartifacts/8bits/ss-5818_tvmdlr_ti-robokit_edgeai-tv_deeplabv3plus_mobilenetv2_tv_edgeailite_robokit-zed1hd_768x432_qat-p2_onnx.tar.gz.link/artifacts: 不是目录
Entering: ./work_dirs/modelartifacts/8bits/od-5120_tvmdlr_coco_tf1-models_ssdlite_mobiledet_dsp_320x320_coco_20200519_tflite.tar.gz.link
run_set_target_machine.sh: 第 59 行: cd: ./work_dirs/modelartifacts/8bits/od-5120_tvmdlr_coco_tf1-models_ssdlite_mobiledet_dsp_320x320_coco_20200519_tflite.tar.gz.link/artifacts: 不是目录
Entering: ./work_dirs/modelartifacts/8bits/cl-3520_tvmdlr_imagenet1k_tf1-models_mobilenet_v1_1.0_224_tflite.tar.gz.link
run_set_target_machine.sh: 第 59 行: cd: ./work_dirs/modelartifacts/8bits/cl-3520_tvmdlr_imagenet1k_tf1-models_mobilenet_v1_1.0_224_tflite.tar.gz.link/artifacts: 不是目录
Entering: ./work_dirs/modelartifacts/8bits/cl-3430_tvmdlr_imagenet1k_gluoncv-mxnet_xception-symbol_json.tar.gz.link
run_set_target_machine.sh: 第 59 行: cd: ./work_dirs/modelartifacts/8bits/cl-3430_tvmdlr_imagenet1k_gluoncv-mxnet_xception-symbol_json.tar.gz.link/artifacts: 不是目录
Entering: ./work_dirs/modelartifacts/8bits/cl-3110_tvmdlr_imagenet1k_torchvision_resnet50_onnx.tar.gz.link
run_set_target_machine.sh: 第 59 行: cd: ./work_dirs/modelartifacts/8bits/cl-3110_tvmdlr_imagenet1k_torchvision_resnet50_onnx.tar.gz.link/artifacts: 不是目录
Entering: ./work_dirs/modelartifacts/8bits/cl-3098_tvmdlr_imagenet1k_torchvision_mobilenet_v2_tv_qat-p2_onnx.tar.gz.link
run_set_target_machine.sh: 第 59 行: cd: ./work_dirs/modelartifacts/8bits/cl-3098_tvmdlr_imagenet1k_torchvision_mobilenet_v2_tv_qat-p2_onnx.tar.gz.link/artifacts: 不是目录
Entering: ./work_dirs/modelartifacts/8bits/cl-3530_tvmdlr_imagenet1k_tf1-models_resnet50_v1_tflite.tar.gz.link
run_set_target_machine.sh: 第 59 行: cd: ./work_dirs/modelartifacts/8bits/cl-3530_tvmdlr_imagenet1k_tf1-models_resnet50_v1_tflite.tar.gz.link/artifacts: 不是目录
Entering: ./work_dirs/modelartifacts/8bits/od-5100_tvmdlr_coco_mlperf_ssd_mobilenet_v1_coco_20180128_tflite.tar.gz.link
run_set_target_machine.sh: 第 59 行: cd: ./work_dirs/modelartifacts/8bits/od-5100_tvmdlr_coco_mlperf_ssd_mobilenet_v1_coco_20180128_tflite.tar.gz.link/artifacts: 不是目录
Entering: ./work_dirs/modelartifacts/8bits/cl-3480_tvmdlr_imagenet1k_gluoncv-mxnet_hrnet_w18_small_v2_c-symbol_json.tar.gz.link
run_set_target_machine.sh: 第 59 行: cd: ./work_dirs/modelartifacts/8bits/cl-3480_tvmdlr_imagenet1k_gluoncv-mxnet_hrnet_w18_small_v2_c-symbol_json.tar.gz.link/artifacts: 不是目录
Entering: ./work_dirs/modelartifacts/8bits/cl-3410_tvmdlr_imagenet1k_gluoncv-mxnet_mobilenetv2_1.0-symbol_json.tar.gz.link
run_set_target_machine.sh: 第 59 行: cd: ./work_dirs/modelartifacts/8bits/cl-3410_tvmdlr_imagenet1k_gluoncv-mxnet_mobilenetv2_1.0-symbol_json.tar.gz.link/artifacts: 不是目录
TIDL_TOOLS_PATH=/home/valeo22/edgeai-benchmark/tidl_tools
LD_LIBRARY_PATH=/home/valeo22/edgeai-benchmark/tidl_tools
PYTHONPATH=:
===================================================================
/home/valeo22/edgeai-benchmark/edgeai_benchmark/datasets/__init__.py:52: UserWarning: kitti_lidar_det could not be imported - No module named 'edgeai_benchmark.datasets.kitti_object_eval_python'
  warnings.warn(f'kitti_lidar_det could not be imported - {str(e)}')
work_dir = ./work_dirs/modelartifacts/8bits
packaged_dir = ./work_dirs/modelartifacts_package/8bits
loading annotations into memory...
Done (t=0.35s)
creating index...
index created!
loading annotations into memory...
Done (t=0.42s)
creating index...
index created!
Traceback (most recent call last):
  File "./scripts/benchmark_custom.py", line 292, in <module>
    tools.run_accuracy(settings, work_dir, pipeline_configs)
  File "/home/valeo22/edgeai-benchmark/edgeai_benchmark/tools/run_accuracy.py", line 50, in run_accuracy
    pipeline_runner = pipelines.PipelineRunner(settings, pipeline_configs)
  File "/home/valeo22/edgeai-benchmark/edgeai_benchmark/pipelines/pipeline_runner.py", line 66, in __init__
    if self._check_model_selection(self.settings, pipeline_config):
  File "/home/valeo22/edgeai-benchmark/edgeai_benchmark/pipelines/pipeline_runner.py", line 208, in _check_model_selection
    assert dataset_category is not None, f'dataset_selection is set, but dataset_category is not defined in pipeline_config: {pipeline_config}'
AssertionError: dataset_selection is set, but dataset_category is not defined in pipeline_config: {'task_type': 'detection', 'calibration_dataset': <edgeai_benchmark.datasets.coco_det.COCODetection object at 0x7f39f2636e80>, 'input_dataset': <edgeai_benchmark.datasets.coco_det.COCODetection object at 0x7f395d2af470>, 'preprocess': <edgeai_benchmark.preprocess.PreProcessTransforms object at 0x7f39877b0be0>, 'session': <edgeai_benchmark.sessions.onnxrt_session.ONNXRTSession object at 0x7f39877b0c50>, 'postprocess': <edgeai_benchmark.postprocess.PostProcessTransforms object at 0x7f39438a9278>, 'metric': {'label_offset_pred': {0: 1, 1: 2, 2: 3, 3: 4, 4: 5, 5: 6, 6: 7, 7: 8, 8: 9, 9: 10, 10: 11, 11: 13, 12: 14, 13: 15, 14: 16, 15: 17, 16: 18, 17: 19, 18: 20, 19: 21, 20: 22, 21: 23, 22: 24, 23: 25, 24: 27, 25: 28, 26: 31, 27: 32, 28: 33, 29: 34, 30: 35, 31: 36, 32: 37, 33: 38, 34: 39, 35: 40, 36: 41, 37: 42, 38: 43, 39: 44, 40: 46, 41: 47, 42: 48, 43: 49, 44: 50, 45: 51, 46: 52, 47: 53, 48: 54, 49: 55, 50: 56, 51: 57, 52: 58, 53: 59, 54: 60, 55: 61, 56: 62, 57: 63, 58: 64, 59: 65, 60: 67, 61: 70, 62: 72, 63: 73, 64: 74, 65: 75, 66: 76, 67: 77, 68: 78, 69: 79, 70: 80, 71: 81, 72: 82, 73: 84, 74: 85, 75: 86, 76: 87, 77: 88, 78: 89, 79: 90, 80: 91}}, 'model_info': {'metric_reference': {'accuracy_ap[.5:.95]%': 37.4}}}
-------------------------------------------------------------------
===================================================================
/home/valeo22/edgeai-benchmark/edgeai_benchmark/datasets/__init__.py:52: UserWarning: kitti_lidar_det could not be imported - No module named 'edgeai_benchmark.datasets.kitti_object_eval_python'
  warnings.warn(f'kitti_lidar_det could not be imported - {str(e)}')
settings: {'include_files': None, 'pipeline_type': 'accuracy', 'num_frames': 10000, 'calibration_frames': 50, 'calibration_iterations': 50, 'configs_path': './configs', 'models_path': '../edgeai-modelzoo/models', 'modelartifacts_path': './work_dirs/modelartifacts', 'datasets_path': './dependencies/datasets', 'target_device': None, 'target_machine': 'pc', 'run_suffix': None, 'parallel_devices': [0], 'tensor_bits': 8, 'runtime_options': None, 'run_import': True, 'run_inference': True, 'run_missing': True, 'detection_threshold': 0.3, 'detection_top_k': 200, 'detection_nms_threshold': None, 'detection_keep_top_k': None, 'save_output': False, 'num_output_frames': 50, 'model_selection': ['onnx'], 'model_exclusion': None, 'task_selection': 'detection', 'runtime_selection': 'onnxrt', 'session_type_dict': {'onnx': 'onnxrt', 'tflite': 'tflitert', 'mxnet': 'tvmdlr'}, 'dataset_type_dict': {'imagenet': 'imagenetv2c'}, 'dataset_selection': 'coco', 'dataset_loading': True, 'config_range': None, 'enable_logging': True, 'verbose': False, 'capture_log': False, 'experimental_models': False, 'rewrite_results': False, 'with_udp': True, 'flip_test': False, 'model_transformation_dict': None, 'report_perfsim': False, 'tidl_offload': True, 'input_optimization': None, 'run_dir_tree_depth': None, 'settings_file': 'settings_import_on_pc.yaml', 'basic_keys': ['include_files', 'pipeline_type', 'num_frames', 'calibration_frames', 'calibration_iterations', 'configs_path', 'models_path', 'modelartifacts_path', 'datasets_path', 'target_device', 'target_machine', 'run_suffix', 'parallel_devices', 'tensor_bits', 'runtime_options', 'run_import', 'run_inference', 'run_missing', 'detection_threshold', 'detection_top_k', 'detection_nms_threshold', 'detection_keep_top_k', 'save_output', 'num_output_frames', 'model_selection', 'model_exclusion', 'task_selection', 'runtime_selection', 'session_type_dict', 'dataset_type_dict', 'dataset_selection', 'dataset_loading', 'config_range', 'enable_logging', 'verbose', 'capture_log', 'experimental_models', 'rewrite_results', 'with_udp', 'flip_test', 'model_transformation_dict', 'report_perfsim', 'tidl_offload', 'input_optimization', 'run_dir_tree_depth', 'settings_file'], 'dataset_cache': None}
no results found - no report to generate.
Report generated at ./work_dirs/modelartifacts
-------------------------------------------------------------------


and my pipeline_configs is as follows:
![2022-12-02 16-23-09屏幕截图](https://user-images.githubusercontent.com/111262872/205249978-760e96fb-afe2-48b9-91cf-0bdbcd5e2ade.png)
 

I am glad to expect your reply! 
Thanks

**Comment by Onehundred0906** [comment]
Hello, I'm sorry to bother you again, but when I compile my model trained on my own datasets, some mistake occurs like that:
![2022-12-02 16-34-31屏幕截图](https://user-images.githubusercontent.com/111262872/205251345-cb8ebb8e-e77f-448e-ac45-1808063631e9.png)
![2022-12-02 16-34-53屏幕截图](https://user-images.githubusercontent.com/111262872/205251354-60ece48f-ba27-4ef9-a007-676dc5994a86.png)
![2022-12-02 16-35-20屏幕截图](https://user-images.githubusercontent.com/111262872/205251360-ad9190aa-4210-469e-81f0-59765a57fb7b.png)

and my pipeline_configs is defined as follows:
![2022-12-02 16-36-05屏幕截图](https://user-images.githubusercontent.com/111262872/205251509-33c4236b-6810-4570-9656-48cb34681cc5.png)
can you help me solute my blocks? i'm very glad to expect your reply!
very Thanks.

**Comment by Onehundred0906** [comment]
i'm sorry, ‘不是目录’ is present ‘Not a directory’in the first picture !

**Comment by mathmanu** [comment]
The assertion error seems to be saying that:
dataset_selection is set, but dataset_category is not defined in pipeline_config:

Is this the error that you are referring to?

Wondering why dataset_selection is set. Have you set dataset_selection in settings_base.yaml by any chance?

**Comment by Onehundred0906** [comment]
emmm, i change the dataset_selection as coco, the follows is mine
![2022-12-02 17-34-05屏幕截图](https://user-images.githubusercontent.com/111262872/205261919-8b08d8d3-9057-4720-8a15-1171c6a000b7.png)

thanks for your reply！

**Comment by mathmanu** [comment]
If you set dataset_selection to default value (null), are you able to run the script?

**Comment by Onehundred0906** [comment]
yeah   i have tried that you said,  the mistake didn't occur, but i don't know why the compile time is so long so long? i can set somewhat to decrease the compile time? expect to reply!
 
very thanks!
![2022-12-02 21-16-24屏幕截图](https://user-images.githubusercontent.com/111262872/205302287-a792f2cd-548d-498a-bca1-1ad4f47c2c54.png)
![2022-12-02 21-16-41屏幕截图](https://user-images.githubusercontent.com/111262872/205302297-e9864ffb-9ba4-450b-b0cf-b40c9c7e061b.png)

**Comment by Onehundred0906** [comment]
Thanks for your help. i have completed the compile process, but i have some questions that need your help.
1. the 'run_import' and 'run_inference' present what, or tell me how to set them? True or False
![2022-12-02 23-41-27屏幕截图](https://user-images.githubusercontent.com/111262872/205331371-329635ba-0ef6-4778-a9e0-5cf0c69502f9.png)

2. what's the function of the params('num_frames' and 'calibration_frames'), and i should how to set them, i guess they influence the precision of model-deploying?
![2022-12-02 23-42-01屏幕截图](https://user-images.githubusercontent.com/111262872/205332240-5ca163a1-0b2d-4061-8388-ce6432b2141c.png)
i expect your soon reply ! very thanks!

**Comment by mathmanu** [comment]
calibration_... parameters influences the import time and accuracy. Reducing these may reduce accuracy for some models. 25, 25 may give good results, but for quick experimentation you can use 10, 10 as you have shown above.
num_frames determines the number frames used for inference.

**Comment by Onehundred0906** [comment]
Thanks for your reply
