### ISSUE TITLE
ModuleNotFoundError: No module named 'osrt_model_tools'

### ISSUE THREAD

**Issue by suyali** [TexasInstruments/edgeai-benchmark#8]
I dowoload ./tutorials/tutorial_detection.ipynb and run ./tutorials/tutorial_detection.py ,then got the error:ModuleNotFoundError: No module named 'osrt_model_tools'
all the information followed as this:
Downloading 1/1: /mnt/data/edgeai-modelzoo/models/vision/detection/coco/mlperf/ssd_mobilenet_v1_coco_20180128.tflite
Download done for /mnt/data/edgeai-modelzoo/models/vision/detection/coco/mlperf/ssd_mobilenet_v1_coco_20180128.tflite

No module named 'osrt_model_tools'
Traceback (most recent call last):
  File "/mnt/data/edgeai-benchmark/jai_benchmark/pipelines/pipeline_runner.py", line 136, in _run_pipeline
    accuracy_result = accuracy_pipeline(description)
  File "/mnt/data/edgeai-benchmark/jai_benchmark/pipelines/accuracy_pipeline.py", line 93, in __call__
    self.session.start()
  File "/mnt/data/edgeai-benchmark/jai_benchmark/sessions/basert_session.py", line 135, in start
    self.get_model()
  File "/mnt/data/edgeai-benchmark/jai_benchmark/sessions/basert_session.py", line 391, in get_model
    optimization_done = self._optimize_model(is_new_file=(not model_file_exists))
  File "/mnt/data/edgeai-benchmark/jai_benchmark/sessions/basert_session.py", line 430, in _optimize_model
    from osrt_model_tools.tflite_tools import tflite_model_opt as tflopt
ModuleNotFoundError: No module named 'osrt_model_tools'
TASKS                                                       | 100%|##########|| 1/1 [00:07<00:00,  7.99s/it]

what should I do?

**Comment by mathmanu** [comment]
The Python package osrt_model_tools is installed by this line: https://github.com/TexasInstruments/edgeai-benchmark/blob/master/requirements_pc.txt#L21

You install it manually as well:

pip install git+https://github.com/TexasInstruments/edgeai-tidl-tools.git#subdirectory=scripts
